# Site
title: gnulinuxmate
description: A typical Linux blog
url: 
logo: halve.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.jpg                           # this image will be shown on homepage's left block
  post-list: images/home.jpg             # this image will be shown on post list page
  default-post: images/home.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          pretty
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-131121845-1

#disqus
disqus: gnulinuxmate

# Social Links
#email:             vinu@linuxmate.ml
#google.plus:        username
twitter:            kevy_vinu
#facebook:           username
github:             kevydotvinu
stackoverflow:     367967/kevy
linkedin:          vinu-k
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:           UCI4pT-mOo-UX5IfGVRtOLlw
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
