backend:
  name: github
  repo: kevydotvinu/kevydotvinu.github.io
  branch: netlifycms
  base_url: https://netlifycms-kevy.herokuapp.com

media_folder: "images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Category", name: "category", widget: "hidden", default: "posts"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma", required: true}
      - {label: "Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Share Image", name: "share-img", widget: "image", required: true, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "SEO description", name: "excerpt", widget: "text", required: true}
      - {label: "SEO tags (space delimiter)", name: "tags", widget: "string", required: true}
#   card: {type: "image", image: "image", text: "title", required: true}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Gists"
        name: "gists"
        file: "gists.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "gists"}
          - {label: "Image", name: "image", widget: "image", required: false, tagname: ""}
          - {label: "Share Image", name: "share-img", widget: "image", required: true, tagname: ""}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO description", name: "excerpt", widget: "text", required: true}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Profile"
        name: "profile"
        file: "profile.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "porfolio"}
          - {label: "Image", name: "image", widget: "image", required: false, tagname: ""}
          - {label: "Share Image", name: "share-img", widget: "image", required: true, tagname: ""}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO description", name: "excerpt", widget: "text", required: true}
          - {label: "Body", name: "body", widget: "markdown"}
